### ISSUE TITLE
/spawn doesn't work anymore

### ISSUE THREAD

**Issue by sennewood** [toddharrison/PlayerState#1]
Server: Canary Nightly No.708

I have two worlds on my server, but after I installed the plugin I can't switch with /spawn to my other world. Even after I deactivated the plugin I can't switch to my other world. The coordinates are correct, but the server doesn't load the other world anymore.

**Comment by toddharrison** [comment]
Is the world configured to autoload? If not then you need to change the configuration of that world to make it load. You can also run the command `/loadworld` to bring it up from the console.

In regard to this bug, `/spawn` should take you to the spawn of the world you are in, and `/spawn otherWorld` should take you to that world. Is this not working?

Please let me know if this resolves your issues.

**Comment by sennewood** [comment]
While I setup my worlds I spawned back and forward and load the second world via /loadword. All that works as it should. But after activating the plugin:

I'm in worldA at 200,100,400
"/spawn worldB" ports me to WorldA at 0,4,0
0,4,0 are the spawn coordinates in WorldB

That's what I meant with the server didn't changed the world.

**Comment by toddharrison** [comment]
Please take a look inside of the playerstate database xml file. If the data for the world your in has a spawn value set, make sure that's the correct value that you expect. If not, let's try deleting that data file and trying again. If you need you can provide me a pastebin of the playerstate xml data and I can help diagnose the issue.

**Comment by sennewood** [comment]
playerstate_player.xml: http://pastebin.com/MGaPfW0Y

**Comment by Nutmegan** [comment]
I had this problem at first as well but I thought it was fixed because I'm not seeing it anymore. Out of curiosity, what CanarySnapshot are you using? Also, I think I asked this before, but do you have ExactSpawn loaded? Also, are you Op'd when you see this issue? Or have you died when it happens?

I'll see if I can reproduce this again on my own set-up to help debug.

**Comment by toddharrison** [comment]
Looks like there may be a bug related to creating a home for you if you don't have one set when you change worlds. I'll do some additional testing. I'll also try to replicate what you're seeing based on the pastebin. In the meantime, try removing the playerstate xml after stopping the server. See if that makes any difference.

**Comment by sennewood** [comment]
It doesn't makes a difference.

PlayerState is the only plugin, no Exact Spawn. I'm OP and in spectator mode, because I would die.

Server: first "Nightly 710", now 727.

**Comment by toddharrison** [comment]
and you have automate=false?

**Comment by sennewood** [comment]
Yes, see #2

**Comment by toddharrison** [comment]
Confirmed the issue. Working on a fix. Apparently it has something to do with a bed being set for the player. If you create a bed and sleep in it then suddenly the spawn will work to go to each world. It would also seem that home is being autoset for the player as well.
Here's how I'm thinking that it should work when automate=false. There should be a global home for the player, across all worlds. Spawn should allow you to return to spawn in either world. Does this match with your expectations?

**Comment by sennewood** [comment]
We have a lobby world ("default") for our canary server, so your solution is fine for me.

**Comment by toddharrison** [comment]
I believe some of these issues have now been addressed. Please try out 0.2.0 and let me know if you still have issues. Try logging out and logging back in if `/spawn <world>` seems to stop working. I think there is a Minecraft client bug involved.
