### ISSUE TITLE
Feature: Saves for groups of worlds

### ISSUE THREAD

**Issue by sennewood** [toddharrison/PlayerState#3]
It would be nice to define groups of worlds where a playerstate is shared.

WorldA
WorldB
WorldC
= Save 1

WorldD
WorldE
WorldF
= Save 2

**Comment by toddharrison** [comment]
Good idea. I'll take a look.

**Comment by sennewood** [comment]
You could handle single Worlds as a group as well all worlds which doesn't shall be affected by the plugin.

**Comment by toddharrison** [comment]
Feature added in 0.2.0.
